### ISSUE TITLE
Adding support for Si

### ISSUE THREAD

**Issue by kealanf** [scotthartley/blmol#4]
Hey! Love this script! Any chance you could include support for silicon? I tried adding it to the ATOMIC_NUMBERS, ELEMENT_COLORS and RADII arrays but I still get the error
```
File "<blender_console>", line 1, in <module>
  File "/Applications/Blender/blender.app/Contents/Resources/2.79/scripts/modules/blmol.py", line 556, in read_pdb
KeyError: 'SI'
```
Thanks for your help!

**Comment by kealanf** [comment]
Closing blender and re-importing the script got it working! Sorry to bother you!

**Comment by scotthartley** [comment]
No problem. Glad you got it working!
