### ISSUE TITLE
Reading problems

### ISSUE THREAD

**Issue by ilyavpro** [scotthartley/blmol#5]
Hello! Thank you for your article on creating molecular orbitals. Could you tell me why the program is giving an error.

![image](https://user-images.githubusercontent.com/69986605/90813918-b955aa80-e341-11ea-8e5c-e02530d8a867.png)
![image](https://user-images.githubusercontent.com/69986605/90813943-c6729980-e341-11ea-88d2-cefcaa78f21a.png)
![image](https://user-images.githubusercontent.com/69986605/90813983-d7230f80-e341-11ea-9db0-b489e031874f.png)

The model was created in jmol according to the instructions and is opened using Blender Atomic. However, Blender Atomic does not fit my needs. Thank!

**Comment by scotthartley** [comment]
Are you using the most recent version of blmol (from github, not the blog post)? I think your problem may be that you are still using the version that worked with Blender <2.8. I had to make a bunch of changes to fix problems like this a few months ago. I can confirm that it works with the current version (2.83.5).

**Comment by ilyavpro** [comment]
Yes, version from github


> Вы используете самую последнюю версию blmol (из github, а не из блога)? Я думаю, ваша проблема может заключаться в том, что вы все еще используете версию, которая работала с Blender <2.8. Несколько месяцев назад мне пришлось внести кучу изменений, чтобы исправить подобные проблемы. Могу подтвердить, что он работает с текущей версией (2.83.5).

**Comment by scotthartley** [comment]
The error message that you got only makes sense if you are using an older version of the script: for example, line 251 does not contain that bpy.ops.transform.rotate command in the current version, but it used to in versions of the script from a few years ago. I'd suggest deleting it completely and installing the most recent version from github fresh.

**Comment by ilyavpro** [comment]
> The error message that you got only makes sense if you are using an older version of the script: for example, line 251 does not contain that bpy.ops.transform.rotate command in the current version, but it used to in versions of the script from a few years ago. I'd suggest deleting it completely and installing the most recent version from github fresh.

Thanks, the problem was solved by rebooting. However, the resulting model is not suitable for MMOs. This error appears

![image](https://user-images.githubusercontent.com/69986605/90893415-5bc06d00-e3d8-11ea-828c-b461ae18dc1b.png)
![image](https://user-images.githubusercontent.com/69986605/90893417-5cf19a00-e3d8-11ea-9b0f-e5a14ec3a488.png)

However, another problem arose, instead of a framework convenient for MMOs, Johannes van der Waals spheres appeared.

![image](https://user-images.githubusercontent.com/69986605/90893636-c671a880-e3d8-11ea-8ac5-f44ab08a162a.png)

However, it is not imported.
![image](https://user-images.githubusercontent.com/69986605/90894734-7eec1c00-e3da-11ea-9244-2621ed21dc19.png)

**Comment by scotthartley** [comment]
You would use the “m.draw_bonds()” command to get structures that 
would work with MOs or other surfaces.

I’m not exactly sure what you’re doing with the second part. blmol 
can’t import data from jmol. It’s really just a program for 
generating molecular geometries. Instead, you have to import the files 
generated by jmol into Blender itself. I’m afraid I can’t be much 
help beyond the blog post from a few years ago. I don’t do this very 
much and have not tried since Blender 2.8 changed around the interface.

**Comment by ilyavpro** [comment]
@scotthartley 

Thank you very much - that's what you need!

I'm just a beginner chemist, so I didn't know the features of the program and thought that changing the view in jmol should have helped.

I didn’t know about the m.draw_bonds () command, could you tell me where you can find a complete list of commands.

Thanks again.
![image](https://user-images.githubusercontent.com/69986605/90925330-77dd0200-e40a-11ea-835f-154785f14713.png)
![image](https://user-images.githubusercontent.com/69986605/90927013-a90b0180-e40d-11ea-80ce-aa4377e1af6c.png)

**Comment by scotthartley** [comment]
Honestly, the best way to get the list of commands and options is to use 
the autocomplete in Blender. I believe this is just the tab key by 
default. So, if you have already set m = blmol.Molecule(), and then type 
`m.<tab>`, you should see the list of commands. If you type 
`m.draw_bonds(<tab>` you will see the options available for the 
draw_bonds command.
