### ISSUE TITLE
VISUALIZATION: CHGCAR

### ISSUE THREAD

**Issue by quantumable** [scotthartley/blmol#6]
do we have a script to convert it to a .cub file?

**Comment by scotthartley** [comment]
No, I'm afraid this script is really only for importing molecular geometries from pdb files.

**Comment by quantumable** [comment]
>thank you. i was talkin about bmol to visualize charge density

`thank you. i was talkin about bmol to visualize charge density`

**Comment by scotthartley** [comment]
I'm afraid it only imports geometries. You will need another method to load the surface data into Blender.
